swagger: "2.0"
info:
  version: 1.0.0
  title: Live Show Seller
  description: Live Show Seller RESTful Web API Server
  termsOfService: N/A
  contact:
    name: API Support
    url: N/A
    email: tech@algotech.app
consumes:
  - application/json
produces:
  - application/json

basePath: /

paths:
  /:
    get:
      x-swagger-router-controller: api.utilities.test
      operationId: hello
      responses:
        "200":
          description: OK
  /{echo_me}/:
    get:
      x-swagger-router-controller: api.utilities.test
      operationId: echo
      parameters:
        - name: echo_me
          in: path
          description: A string to print back
          required: true
          type: string
      responses:
        "200":
          description: OK
  /test/{user_id}/{product_id}:
    get:
      x-swagger-router-controller: api.utilities.test
      operationId: user_id_and_product_id
      parameters:
        - name: user_id
          in: path
          required: true
          type: string
        - name: product_id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK
  /test/data:
    get:
      x-swagger-router-controller: api.utilities.test
      operationId: show_data
      responses:
        "200":
          description: OK
  