build-job:
    stage: build
    image: python:latest
    before_script:
        - python --version  # For debugging
        - pip install poetry
    script: echo "build"

unit-test:
    stage: test
    script: echo "unit-test"

lint-test:
    stage: test
    script: echo "lint-test"


deploy-app:
  stage: deploy
  script: echo "deploment"
