build-job:
    stage: build
    before_script:
        - apt update
        - apt install python3 -y
        - python3 --version  # For debugging
        - pip install poetry
    script:
        - pwd 
        - echo "build"

unit-test:
    stage: test
    script: echo "unit-test"

lint-test:
    stage: test
    script: echo "lint-test"


deploy-app:
  stage: deploy
  script: echo "deploment"
