build-job:
    stage: build
    image: python:3.8.15
    before_script:
        - python3 --version  # For debugging
        - pip install poetry
    script:
        - pwd 
        - echo "build"

unit-test:
    stage: test
    script: echo "unit-test"

lint-test:
    stage: test
    script: echo "lint-test"


deploy-app:
  stage: deploy
  script: echo "deploment"
