DJANGO_SETTINGS='lss.settings'
POETRY_ENVIRONMENT='/home/lss_env/lib/python3.9/site-packages'

MONGO_DB_USERNAME='lss'
MONGO_DB_PASSWORD= 'algo83111T%%'
MONGO_DB_AUTH_SOURCE= 'lss'

COMMENT_CAPTURE_NODE_NAME = 'TW1'