# Generated by Django 3.2.8 on 2021-11-03 04:35

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_req', models.TextField(blank=True, default=None, null=True)),
                ('message_res', models.TextField(blank=True, default=None, null=True)),
                ('message_type', models.TextField(blank=True, default=None, null=True)),
                ('message_des', models.TextField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('live_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('embed_url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('user_id_added', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('platform_meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('platform_meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_orders', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('order_code', models.CharField(blank=True, max_length=255, null=True)),
                ('product_quantity', models.IntegerField(default=None, null=True)),
                ('product_order_amount', models.IntegerField(default=None, null=True)),
                ('max_order_amount', models.IntegerField(default=None, null=True)),
                ('customer_removable', models.BooleanField(default=None, null=True)),
                ('customer_editable', models.BooleanField(default=None, null=True)),
                ('product_active_stat', models.IntegerField(default=None, null=True)),
                ('platform_meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('payment_meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_quantity', models.IntegerField(default=None, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('order_stat', models.IntegerField(default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.campaign')),
                ('campaign_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.campaigncomment')),
                ('campaign_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.campaignorder')),
                ('campaign_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.campaignproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='api.product'),
        ),
        migrations.CreateModel(
            name='CampaignLuckyDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=255, null=True)),
                ('num_of_winner', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_set', models.TextField(blank=True, default=None, null=True)),
                ('winner_list', models.TextField(blank=True, default=None, null=True)),
                ('platform_meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_lucky_draws', to='api.campaign')),
                ('campaign_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_lucky_draws', to='api.campaignproduct')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.user'),
        ),
    ]
