# Generated by Django 3.2.8 on 2021-11-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncomment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
