# Generated by Django 3.2.8 on 2022-04-07 11:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='credit_card_info',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='type',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('premium', 'Premium'), ('pay per use', 'Pay Per Use'), ('dealer', 'Dealer')], default='trial', max_length=255, null=True),
        ),
    ]
