# Generated by Django 3.2.8 on 2022-12-06 09:11

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignproduct',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_dev_bucket/static/no_image.jpeg', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='original_plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('pro', 'Pro'), ('premium', 'Premium'), ('dealer', 'Dealer'), ('kol', 'Kol')], max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchased_plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('pro', 'Pro'), ('premium', 'Premium'), ('dealer', 'Dealer'), ('kol', 'Kol')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_dev_bucket/static/no_image.jpeg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='type',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('pro', 'Pro'), ('premium', 'Premium'), ('dealer', 'Dealer'), ('kol', 'Kol')], default='trial', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='type',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('pro', 'Pro'), ('premium', 'Premium'), ('dealer', 'Dealer'), ('kol', 'Kol')], default='trial', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_sign', models.CharField(blank=True, default='$', max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('deleted', 'Deleted')], default='new', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('meta_logistic', djongo.models.fields.JSONField(blank=dict, default=dict, null=True)),
                ('lang', models.CharField(choices=[('en', 'English'), ('id', 'Indonesian'), ('zh_hans', 'Chinese-Simplify'), ('zh_hant', 'Chinese-Tranditional'), ('vi', 'Vietnamese')], default='en', max_length=255)),
                ('price_unit', models.CharField(blank=True, choices=[('1', '1'), ('10', '10'), ('100', '100'), ('1000', '1000'), ('10000', '10000'), ('100000', '100000'), ('1000000', '1000000')], default='1', max_length=255)),
                ('decimal_places', models.IntegerField(choices=[(-3, '1000'), (-2, '100'), (-1, '10'), (0, '1'), (1, '0.1'), (2, '0.01')], default=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='api.user')),
            ],
            options={
                'db_table': 'api_supplier',
            },
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_products', to='api.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.supplier'),
        ),
    ]
