# Generated by Django 3.2.8 on 2022-01-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='live_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='page_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
