# Generated by Django 3.2.8 on 2021-11-03 04:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meta', djongo.models.fields.JSONField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
