# Generated by Django 3.2.8 on 2022-12-01 03:42

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.IntegerField(blank=True, default=0, null=True)),
                ('used', models.IntegerField(blank=True, default=0, null=True)),
                ('expired_at', models.DateTimeField(default=None, null=True)),
                ('used_calculated', models.BooleanField(default=False)),
                ('expired_calculated', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='customer_purchase', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_point_transaction',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('manager', 'Manager'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='license',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_dev_bucket/static/no_image.jpeg', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_dev_bucket/static/no_image.jpeg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('customer', 'Customer')], default='customer', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_transactions', to='api.user'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_transactions', to='api.order'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_transactions', to='api.usersubscription'),
        ),
    ]
