# Generated by Django 3.2.8 on 2022-03-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='root_users',
        ),
    ]
