# Generated by Django 3.2.8 on 2021-11-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211116_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncomment',
            name='commented_at',
        ),
    ]
