# Generated by Django 3.2.8 on 2021-11-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211027_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='json',
            field=models.JSONField(default=None, null=True),
        ),
    ]
