# Generated by Django 3.2.8 on 2022-11-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221129_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpoint',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_points', to='api.order'),
        ),
    ]
