# Generated by Django 3.2.8 on 2022-01-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220104_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='channel_id',
        ),
    ]
