# Generated by Django 3.2.8 on 2022-12-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221206_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New')], default='new', max_length=255),
        ),
    ]
