# Generated by Django 3.2.8 on 2021-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('order', 'In order'), ('cancel', 'cancelled')], default='New', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('order_code', 'Add from order code in campaign comment'), ('cart', 'Add from cart')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('user', 'User')], default='customer', max_length=255, null=True),
        ),
    ]
