# Generated by Django 3.2.8 on 2022-05-11 08:14

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220511_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncomment',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='categories',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='created_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaigncomment',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
