# Generated by Django 3.2.8 on 2022-03-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usersubscription_root_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.usersubscription'),
        ),
    ]
