# Generated by Django 3.2.8 on 2022-12-12 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221208_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='supplier_subscripiton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperator_campaigns', to='api.usersubscription'),
        ),
    ]
