# Generated by Django 3.2.8 on 2021-12-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_campaign_ordering_only_activated_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='candidate_set',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='winner_list',
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='condition',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('cart_product', 'From Cart Product'), ('campaign_comment', 'From Campaign Comment'), ('campaign_likes', 'From Campaign Likes')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('cart_product', 'Add to Cart Product')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='source_type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('cart_product', 'Cart Product'), ('campaign_comment', 'Campaign Comment'), ('campaign_likes', 'Campaign Likes')], default='n/a', max_length=255),
        ),
    ]
