# Generated by Django 3.2.8 on 2021-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211119_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('ordered', 'In order'), ('voided', 'Cannelled')], default='valid', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('order_code', 'Added from order code in campaign comment'), ('cart', 'Added from cart')], default='n/a', max_length=255),
        ),
    ]
