# Generated by Django 3.2.8 on 2022-01-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_youtubechannel_live_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='customer_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
