# Generated by Django 3.2.8 on 2022-01-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_youtubechannel_live_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramprofile',
            name='bussiness_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
