# Generated by Django 3.2.8 on 2021-11-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaigncomment_commented_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncomment',
            name='meta',
        ),
    ]
