# Generated by Django 3.2.8 on 2022-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220511_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='country',
            field=models.CharField(blank=True, default='SG', max_length=255, null=True),
        ),
    ]
