# Generated by Django 3.2.8 on 2021-12-01 08:05

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211201_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignluckydraw',
            name='candidate_list',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='campaignluckydraw',
            name='winner_list',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
