# Generated by Django 3.2.8 on 2022-03-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='api.usersubscription'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='type',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('premium', 'Premium'), ('pay per use', 'Pay Per Use'), {'dealer', 'Dealer'}], default='trial', max_length=255, null=True),
        ),
    ]
