# Generated by Django 3.2.8 on 2022-12-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_supplier_subscripiton_campaign_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cellphone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
