# Generated by Django 3.2.8 on 2021-12-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211201_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('cart_product', 'Draw from Cart Products'), ('campaign_comment', 'Draw from Campaign Comments'), ('campaign_likes', 'Draw from Campaign Likes')], default='n/a', max_length=255),
        ),
    ]
