# Generated by Django 3.2.8 on 2022-01-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220106_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
