# Generated by Django 3.2.8 on 2021-11-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211119_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Deactivated'), (1, 'Activated')], default=0),
        ),
    ]
