# Generated by Django 3.2.8 on 2021-11-16 11:40

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_campaigncomment_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncomment',
            name='meta',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
