# Generated by Django 3.2.8 on 2021-11-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_campaigncomment_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoresponse',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='candidate_set',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='winner_list',
        ),
        migrations.RemoveField(
            model_name='campaignproduct',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='campaignproduct',
            name='meta_logistic',
        ),
        migrations.RemoveField(
            model_name='campaignproduct',
            name='tag',
        ),
    ]
