# Generated by Django 3.2.16 on 2022-12-21 06:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_shipping_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='meta_variant',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_variant',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_public_bucket/static/no_image.jpeg', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_public_bucket/static/no_image.jpeg', max_length=255, null=True),
        ),
    ]
