# Generated by Django 3.2.8 on 2021-12-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211201_1610'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaignluckydraw',
            table='api_campaign_lucky_draw',
        ),
    ]
