# Generated by Django 3.2.8 on 2021-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_campaignproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('order_code', 'Added from order code in campaign comment'), ('cart', 'Added from cart page function'), ('lucky_draw_cart', 'Added from lucky draw from cart product'), ('lucky_draw_comment', 'Added from lucky draw from campaign comment keyword'), ('lucky_draw_like', 'Added from lucky draw from campaign like')], default='n/a', max_length=255),
        ),
    ]
