# Generated by Django 3.2.8 on 2022-05-20 03:45

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usersubscription_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncomment',
            name='main_categories',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
