# Generated by Django 3.2.8 on 2022-01-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_instagramprofile_bussiness_id'),
        ('api', '0006_auto_20220107_0308'),
    ]

    operations = [
    ]
