# Generated by Django 3.2.8 on 2022-01-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20220111_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='platform_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_address_1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_address_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_company',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_email',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_gender',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_location',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_region',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='tracking',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
