# Generated by Django 3.2.8 on 2021-11-23 03:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cartproduct_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='payment_meta',
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_logistic',
            field=djongo.models.fields.JSONField(blank=dict, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_payment',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='meta_logistic',
            field=djongo.models.fields.JSONField(blank=dict, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='meta_payment',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('valid', 'Valid')], default='new', max_length=255, null=True),
        ),
    ]
