# Generated by Django 3.2.8 on 2021-12-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_campaignluckydraw_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='candidate_list',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='condition_type',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='num_of_winner',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='prize_campaign_product',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='type',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='campaignluckydraw',
            name='winner_list',
        ),
    ]
