# Generated by Django 3.2.8 on 2021-11-16 11:43

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211116_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='facebook_campaign',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='youtube_campaign',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
