# Generated by Django 3.2.8 on 2022-05-30 04:13

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
