# Generated by Django 3.2.8 on 2021-12-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211201_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignLuckyDraw',
        ),
    ]
