# Generated by Django 3.2.8 on 2022-01-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220112_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_address_1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_address_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_company',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_gender',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_location',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_region',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preorder',
            name='payment_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
