# Generated by Django 3.2.8 on 2021-11-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211123_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=255),
        ),
    ]
