# Generated by Django 3.2.8 on 2021-11-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211116_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='meta',
        ),
    ]
