# Generated by Django 3.2.8 on 2021-11-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_facebookpage_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=255),
        ),
    ]
