# Generated by Django 3.2.8 on 2021-12-01 09:34

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_campaignluckydraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLuckyDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, default=None, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('n/a', 'Not available'), ('cart_product', 'Cart Product'), ('campaign_comment', 'Campaign Comment'), ('campaign_likes', 'Campaign Likes')], default='n/a', max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_type', models.CharField(blank=True, choices=[('n/a', 'Not available'), ('cart_product', 'Draw from Cart Products'), ('campaign_comment', 'Draw from Campaign Comments'), ('campaign_likes', 'Draw from Campaign Likes')], default='n/a', max_length=255)),
                ('num_of_winner', models.IntegerField(blank=True, default=1, null=True)),
                ('candidate_list', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('winner_list', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_lucky_draws', to='api.campaign')),
                ('prize_campaign_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_lucky_draws', to='api.campaignproduct')),
            ],
            options={
                'db_table': 'api_campaign_lucky_draw',
            },
        ),
    ]
