# Generated by Django 3.2.16 on 2023-01-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221223_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncomment',
            name='customer_nickname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_nickname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_nickname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_dev_bucket/static/no_image.jpeg', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_dev_bucket/static/no_image.jpeg', max_length=255, null=True),
        ),
    ]
