# Generated by Django 3.2.8 on 2022-05-30 06:57

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('used_at', models.DateTimeField()),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_code', to='api.user')),
                ('user_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_code', to='api.usersubscription')),
            ],
            options={
                'db_table': 'api_promotion_code',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_plan', models.CharField(choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('premium', 'Premium'), ('dealer', 'Dealer')], max_length=255)),
                ('purchased_plan', models.CharField(choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('premium', 'Premium'), ('dealer', 'Dealer')], max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=99)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('processing', 'Processing')], max_length=255)),
                ('payment_time', models.DateTimeField()),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='api.user')),
                ('user_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='api.usersubscription')),
            ],
            options={
                'db_table': 'api_deal',
            },
        ),
    ]
