# Generated by Django 3.2.8 on 2021-11-16 11:44

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cartproduct_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='history',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='meta',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
