# Generated by Django 3.2.8 on 2022-06-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_deal_promotioncode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotioncode',
            old_name='user',
            new_name='api_user',
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('fail', 'Fail'), ('processing', 'Processing')], max_length=255, null=True),
        ),
    ]
