# Generated by Django 3.2.8 on 2022-01-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220113_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
