# Generated by Django 3.2.8 on 2021-11-23 09:56

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211123_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('enabled', 'enabled'), ('disabled', 'disabled'), ('archived', 'archived')], default='enabled', max_length=255),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('facebook_pages', models.ManyToManyField(related_name='user_subscriptions', to='api.FacebookPage')),
                ('users', models.ManyToManyField(related_name='user_subscriptions', to='api.User')),
                ('youtube_channels', models.ManyToManyField(related_name='user_subscriptions', to='api.YoutubeChannel')),
            ],
            options={
                'db_table': 'api_user_subscription',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.usersubscription'),
        ),
    ]
