# Generated by Django 3.2.8 on 2022-06-06 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220606_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_code', to='api.deal'),
        ),
    ]
