# Generated by Django 3.2.8 on 2021-11-16 11:45

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211116_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_logistic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='order',
            name='history',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meta',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
