# Generated by Django 3.2.8 on 2022-01-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orderproduct_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='proceed', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(blank=True, default='review', max_length=255, null=True),
        ),
    ]
