# Generated by Django 3.2.8 on 2021-12-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('lucky_draw_cart_products', 'Draw from Cart Products'), ('lucky_draw_campaign_comments', 'Draw from Campaign Comments'), ('lucky_draw_campaign_likes', 'Draw from Campaign Likes')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('order_code', 'Added from order code in campaign comment'), ('cart', 'Added from cart page function'), ('lucky_draw_cart_products', 'Added from lucky draw of cart product'), ('lucky_draw_campaign_comments', 'Added from lucky draw of campaign comments'), ('lucky_draw_campaign_likes', 'Added from lucky draw of campaign likes')], default='n/a', max_length=255),
        ),
    ]
