# Generated by Django 3.2.8 on 2021-11-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211123_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_products', to='api.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='enabled', max_length=255),
        ),
    ]
