# Generated by Django 3.2.8 on 2022-06-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_promotioncode_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_option',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
