# Generated by Django 3.2.16 on 2023-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_shipping_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_time_slot',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
