# Generated by Django 3.2.8 on 2021-11-16 11:46

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211116_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_logistic',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
