# Generated by Django 3.2.8 on 2021-12-02 11:55

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211202_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='country_meta',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
