# Generated by Django 3.2.8 on 2021-11-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211123_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='users',
            new_name='root_users',
        ),
    ]
