# Generated by Django 3.2.8 on 2022-01-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adjust_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='adjust_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='free_delievery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='adjust_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='adjust_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='free_delievery',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
