# Generated by Django 3.2.8 on 2021-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_usersubscription_country_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncomment',
            name='platform',
            field=models.CharField(blank=True, choices=[('n/a', 'No specific platform'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='platform',
            field=models.CharField(blank=True, choices=[('n/a', 'No specific platform'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.CharField(blank=True, choices=[('n/a', 'No specific platform'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='n/a', max_length=255),
        ),
    ]
