# Generated by Django 3.2.8 on 2022-06-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220614_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='preorder',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
