# Generated by Django 3.2.8 on 2021-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211117_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
