# Generated by Django 3.2.8 on 2022-01-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220120_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='free_delievery',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='free_delievery',
        ),
    ]
