# Generated by Django 3.2.8 on 2022-06-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220614_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='campaign_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='campaign_live_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='channel_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='order_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='product_limit',
            field=models.IntegerField(default=10),
        ),
    ]
