# Generated by Django 3.2.8 on 2021-12-03 09:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211202_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='country_meta',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='meta_logistic',
            field=djongo.models.fields.JSONField(blank=dict, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='meta_payment',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('product', 'Product from inventory'), ('product-fast', 'Product from fast-add'), ('lucky_draw', 'Lucky Draw from inventory'), ('lucky_draw-fast', 'Lucky Draw from fast-add')], default='n/a', max_length=255),
        ),
    ]
