# Generated by Django 3.2.8 on 2022-06-20 04:19

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220616_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='meta',
        ),
    ]
