# Generated by Django 3.2.8 on 2022-01-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220120_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='free_delivery',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
