# Generated by Django 3.2.16 on 2023-02-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='require_customer_login',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
