# Generated by Django 3.2.8 on 2022-01-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220120_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adjust_price',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='adjust_price',
        ),
    ]
