# Generated by Django 3.2.8 on 2021-12-06 12:57

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_usersubscription_meta_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='campaign',
            name='currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_details',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cost_currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='currency_sign',
            field=models.CharField(blank=True, default='$', max_length=255, null=True),
        ),
    ]
