# Generated by Django 3.2.8 on 2022-06-20 04:21

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220620_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='meta',
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
