# Generated by Django 3.2.8 on 2021-11-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'New'), (1, 'Processed')], default=0, max_length=255),
        ),
    ]
