# Generated by Django 3.2.8 on 2021-12-07 07:27

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211206_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('lang', models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_sign', models.CharField(blank=True, default='$', max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, default='Asia/Singapore', max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('token_update_at', models.DateTimeField(null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('meta_payment', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('meta_logistic', djongo.models.fields.JSONField(blank=dict, default=dict, null=True)),
            ],
            options={
                'db_table': 'api_instagram_profile',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='instagram_campaign',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_info',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='instagram_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='api.instagramprofile'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='instagram_profiles',
            field=models.ManyToManyField(related_name='user_subscriptions', to='api.InstagramProfile'),
        ),
    ]
