# Generated by Django 3.2.8 on 2022-06-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220620_0421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
