# Generated by Django 3.2.8 on 2022-01-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220121_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adjust_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='adjust_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
