# Generated by Django 3.2.8 on 2021-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'New'), (1, 'Processed')], default='New', max_length=255),
        ),
    ]
