# Generated by Django 3.2.16 on 2023-03-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230302_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='facebook_campaign_2',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='facebook_page_2',
        ),
    ]
