# Generated by Django 3.2.16 on 2023-03-02 05:32

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230302_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_campaign',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campaigns', to='api.facebookpage'),
        ),
    ]
