# Generated by Django 3.2.8 on 2022-01-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220121_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='campaign_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_products', to='api.campaignproduct'),
        ),
    ]
