# Generated by Django 3.2.8 on 2021-12-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211207_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid item for order'), ('ordered', 'In completed order'), ('staging', 'Staging for completing an order'), ('voided', 'Cannelled')], default='valid', max_length=255),
        ),
    ]
