# Generated by Django 3.2.8 on 2021-12-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_cartproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('id', 'Indonesian')], default='en', max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('id', 'Indonesian')], default='en', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('id', 'Indonesian')], default='en', max_length=255),
        ),
    ]
