# Generated by Django 3.2.16 on 2023-03-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230302_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_option_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
