# Generated by Django 3.2.8 on 2022-01-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_orderproduct_campaign_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='campaign_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='api.campaignproduct'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to='api.campaign'),
        ),
    ]
