# Generated by Django 3.2.8 on 2021-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncomment',
            name='type',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
