# Generated by Django 3.2.8 on 2022-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_campaignproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
