# Generated by Django 3.2.16 on 2023-03-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230306_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='domain',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
