# Generated by Django 3.2.8 on 2021-12-16 02:59

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211216_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('subtotal', models.CharField(blank=True, default='0.00', max_length=255, null=True)),
                ('total', models.CharField(blank=True, default='0.00', max_length=255, null=True)),
                ('currency', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('currency_sign', models.CharField(blank=True, default='$', max_length=255, null=True)),
                ('cost', models.CharField(blank=True, default='0.00', max_length=255, null=True)),
                ('cost_currency', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('cost_currency_sign', models.CharField(blank=True, default='$', max_length=255, null=True)),
                ('platform', models.CharField(blank=True, choices=[('n/a', 'No specific platform'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='n/a', max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('products', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('checkout_details', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('history', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orders', to='api.campaign')),
            ],
            options={
                'db_table': 'api_pre_order',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('order_code', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, choices=[('n/a', 'No specific platform'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='n/a', max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, choices=[('n/a', 'Not available'), ('order_code', 'Added from order code in campaign comment'), ('cart', 'Added from cart page function'), ('lucky_draw_cart_products', 'Added from lucky draw of cart product'), ('lucky_draw_campaign_comments', 'Added from lucky draw of campaign comments'), ('lucky_draw_campaign_likes', 'Added from lucky draw of campaign likes')], default='n/a', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('valid', 'Valid item for order'), ('ordered', 'In completed order'), ('staging', 'Staging for completing an order'), ('voided', 'Cannelled')], default='valid', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='api.campaign')),
                ('campaign_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='api.campaigncomment')),
                ('campaign_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='api.campaignproduct')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.order')),
                ('pre_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.preorder')),
            ],
            options={
                'db_table': 'api_order_product',
            },
        ),
    ]
