# Generated by Django 3.2.8 on 2022-02-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220125_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='page_token',
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='token_update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='token_update_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_products', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='campaign_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_products', to='api.campaignproduct'),
        ),
    ]
