# Generated by Django 3.2.8 on 2021-11-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211117_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigncomment',
            old_name='status',
            new_name='type',
        ),
    ]
