# Generated by Django 3.2.8 on 2022-06-27 10:13

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220627_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignluckydraw',
            name='animation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignluckydraw',
            name='campaign_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_lucky_draws', to='api.campaignproduct'),
        ),
        migrations.AddField(
            model_name='campaignluckydraw',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignluckydraw',
            name='repeatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaignluckydraw',
            name='spin_time',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='campaignluckydraw',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='animations',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='logos',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
