# Generated by Django 3.2.8 on 2021-12-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_orderproduct_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='lock_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(blank=True, default='valid', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('product', 'Product from inventory'), ('product-fast', 'Product from fast-add'), ('lucky_draw', 'Lucky Draw from inventory'), ('lucky_draw-fast', 'Lucky Draw from fast-add')], default='n/a', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('platform', 'customer_id', 'campaign', 'campaign_product')},
        ),
        migrations.AlterUniqueTogether(
            name='preorder',
            unique_together={('platform', 'customer_id', 'campaign')},
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='total',
        ),
    ]
