# Generated by Django 3.2.16 on 2023-06-02 03:29

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_usersubscription_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_campaign_3',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_campaign_4',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_campaign_5',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_campaign_6',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_page_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campaigns_3', to='api.facebookpage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_page_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campaigns_4', to='api.facebookpage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_page_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campaigns_5', to='api.facebookpage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_facebook_page_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campaigns_6', to='api.facebookpage'),
        ),
    ]
