# Generated by Django 3.2.8 on 2021-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_status_campaigncomment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncomment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Processed')], default=0),
        ),
    ]
