# Generated by Django 3.2.8 on 2022-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220627_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='buyer_lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh_hans', 'Simplified Chinese'), ('zh_hant', 'Traditional Chinese'), ('id', 'Indonesian')], default='en', max_length=255),
        ),
    ]
