# Generated by Django 3.2.8 on 2022-02-11 02:43

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220210_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_info',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
