# Generated by Django 3.2.8 on 2022-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_usersubscription_buyer_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='decimal_places',
            field=models.IntegerField(default=2),
        ),
    ]
