# Generated by Django 3.2.8 on 2021-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_campaigncomment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='platform_email',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='platform_id',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
