# Generated by Django 3.2.8 on 2022-06-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usersubscription_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='buyer_lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('id', 'Chinese-Simplify'), ('zh_hans', 'Chinese-Tranditional'), ('zh_hant', 'Indonesian')], default='en', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('TWD', 'TWD'), ('SGD', 'SGD'), ('IDR', 'IDR'), ('PHP', 'PHP'), ('MYR', 'MYR'), ('VND', 'VND'), ('RMB', 'RMB'), ('KHR', 'KHR'), ('AUD', 'AUD'), ('HKD', 'HKD')], default='SGD', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='decimal_places',
            field=models.IntegerField(choices=[(-3, '1000'), (-2, '100'), (0, '1'), (1, '0.1'), (2, '0.01')], default=2),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('id', 'Chinese-Simplify'), ('zh_hans', 'Chinese-Tranditional'), ('zh_hant', 'Indonesian')], default='en', max_length=255),
        ),
    ]
