# Generated by Django 3.2.8 on 2022-03-04 07:22

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220223_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='meta_code',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
