# Generated by Django 3.2.8 on 2022-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220628_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='animations',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='logos',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='decimal_places',
            field=models.IntegerField(choices=[(-3, '1000'), (-2, '100'), (-1, '10'), (0, '1'), (1, '0.1'), (2, '0.01')], default=2),
        ),
    ]
