# Generated by Django 3.2.8 on 2022-03-08 02:50

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_usersubscription_meta_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='user_plan',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
