# Generated by Django 3.2.8 on 2022-06-28 05:01

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220628_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='animations',
            field=djongo.models.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='logos',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
