# Generated by Django 3.2.8 on 2021-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20211220_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
