# Generated by Django 3.2.8 on 2022-06-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220628_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='animations',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='logos',
        ),
    ]
