# Generated by Django 3.2.8 on 2022-03-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_usersubscription_user_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='type',
        ),
    ]
