# Generated by Django 3.2.8 on 2022-07-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220628_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignproduct',
            name='status',
        ),
    ]
