# Generated by Django 3.2.8 on 2022-03-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_usersubscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='type',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('premium', 'Premium'), ('pay per use', 'Pay Per Use')], max_length=255, null=True),
        ),
    ]
