# Generated by Django 3.2.8 on 2022-03-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_usersubscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
