# Generated by Django 3.2.8 on 2022-07-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_campaignproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='qty_add_to_cart',
            field=models.IntegerField(default=0),
        ),
    ]
