# Generated by Django 3.2.8 on 2022-03-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_usersubscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='bussiness_id',
        ),
    ]
