# Generated by Django 3.2.8 on 2022-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_instagramprofile_bussiness_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramprofile',
            name='business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
