# Generated by Django 3.2.8 on 2022-07-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_campaignluckydraw_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_option_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='spin_time',
            field=models.IntegerField(default=5),
        ),
    ]
