# Generated by Django 3.2.8 on 2022-03-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220321_0535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscriptionAdminUsers',
        ),
    ]
