# Generated by Django 3.2.8 on 2022-07-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220714_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='instagram_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_responses', to='api.instagramprofile'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='connected_facebook_page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
