# Generated by Django 3.2.8 on 2022-07-27 08:49

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220722_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignQuizGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('question', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('answer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('num_of_winner', models.IntegerField(blank=True, default=1, null=True)),
                ('repeatable', models.BooleanField(default=True)),
                ('follower', models.BooleanField(default=True)),
                ('winner_list', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_quiz_game', to='api.campaign')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_quiz_game_prize', to='api.campaignproduct')),
            ],
            options={
                'db_table': 'api_campaign_quiz_game',
            },
        ),
    ]
