# Generated by Django 3.2.8 on 2022-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('id', 'Chinese-Simplify'), ('zh_hans', 'Chinese-Tranditional'), ('zh_hant', 'Indonesian')], default='en', max_length=255),
        ),
    ]
