# Generated by Django 3.2.8 on 2022-07-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_campaignquizgame'),
        ('api', '0038_user_lang'),
    ]

    operations = [
    ]
