# Generated by Django 3.2.8 on 2022-07-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_merge_0036_campaignquizgame_0038_user_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignquizgame',
            old_name='follower',
            new_name='is_follower',
        ),
        migrations.AddField(
            model_name='campaign',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('id', 'Chinese-Simplify'), ('zh_hans', 'Chinese-Tranditional'), ('zh_hant', 'Indonesian')], default='en', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lucky_draws', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='campaign_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lucky_draws', to='api.campaignproduct'),
        ),
        migrations.AlterField(
            model_name='campaignluckydraw',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_lucky_draws', to='api.campaignproduct'),
        ),
        migrations.AlterField(
            model_name='campaignquizgame',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_games', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignquizgame',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_games', to='api.campaignproduct'),
        ),
    ]
