# Generated by Django 3.2.8 on 2022-07-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220728_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignquizgame',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='campaignquizgame',
            name='start_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
