# Generated by Django 3.2.8 on 2022-08-01 06:23

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20220729_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignquizgame',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignquizgame',
            name='is_follower',
        ),
        migrations.RemoveField(
            model_name='campaignquizgame',
            name='num_of_winner',
        ),
        migrations.RemoveField(
            model_name='campaignquizgame',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='campaignquizgame',
            name='repeatable',
        ),
        migrations.RemoveField(
            model_name='campaignquizgame',
            name='winner_list',
        ),
        migrations.AddField(
            model_name='campaign',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('1', '1'), ('10', '10'), ('100', '100'), ('1000', '1000'), ('10000', '10000'), ('100000', '100000'), ('1000000', '1000000')], default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('1', '1'), ('10', '10'), ('100', '100'), ('1000', '1000'), ('10000', '10000'), ('100000', '100000'), ('1000000', '1000000')], default='1', max_length=255),
        ),
        migrations.CreateModel(
            name='CampaignQuizGameBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('num_of_winner', models.IntegerField(blank=True, default=1, null=True)),
                ('repeatable', models.BooleanField(default=True)),
                ('is_follower', models.BooleanField(default=True)),
                ('winner_list', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_games', to='api.campaign')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_games', to='api.campaignproduct')),
            ],
            options={
                'db_table': 'api_campaign_quiz_game_bundle',
            },
        ),
    ]
