# Generated by Django 3.2.8 on 2022-08-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220801_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignquizgame',
            name='quiz_game_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_games', to='api.campaignquizgamebundle'),
        ),
        migrations.AlterField(
            model_name='campaignquizgamebundle',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_game_bundle', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignquizgamebundle',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_game_bundle', to='api.campaignproduct'),
        ),
    ]
