# Generated by Django 3.2.8 on 2022-08-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220801_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='decimal_places',
            field=models.IntegerField(choices=[(-3, '1000'), (-2, '100'), (-1, '10'), (0, '1'), (1, '0.1'), (2, '0.01')], default=2),
        ),
    ]
