# Generated by Django 3.2.8 on 2022-08-10 07:55

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_usersubscription_meta_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='meta_plugin',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
