# Generated by Django 3.2.8 on 2022-08-11 07:11

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_usersubscription_meta_plugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_img', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, choices=[('n/a', 'No specific platform'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='n/a', max_length=255)),
                ('platform_id', models.IntegerField(blank=True, default=None, null=True)),
                ('products', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('lock_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('seller_adjust', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
                ('free_delivery', models.BooleanField(default=False, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='api.user')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='api.campaign')),
            ],
            options={
                'db_table': 'api_cart',
                'unique_together': {('platform', 'customer_id', 'campaign')},
            },
        ),
    ]
