# Generated by Django 3.2.8 on 2022-08-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='stop_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
