# Generated by Django 3.2.8 on 2022-08-18 05:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20220816_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_discount',
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_option_data',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='preorder',
            name='applied_discount',
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='preorder',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_option_data',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('limitation', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_code', to='api.usersubscription')),
            ],
            options={
                'db_table': 'api_discount_code',
            },
        ),
    ]
