# Generated by Django 3.2.8 on 2022-08-17 07:41

import api.models.campaign.discount
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20220816_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discount_codes',
            field=djongo.models.fields.ArrayField(default=[], model_container=api.models.campaign.discount.Discount),
        ),
    ]
