# Generated by Django 3.2.8 on 2022-08-17 07:44

import api.models.campaign.discount
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_campaign_discount_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='discount_codes',
            new_name='discounts',
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=djongo.models.fields.ArrayField(default=[], model_container=api.models.campaign.discount.Discount),
        ),
        migrations.AddField(
            model_name='preorder',
            name='discounts',
            field=djongo.models.fields.ArrayField(default=[], model_container=api.models.campaign.discount.Discount),
        ),
    ]
