# Generated by Django 3.2.8 on 2022-08-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20220818_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='limitation',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='api.usersubscription'),
        ),
    ]
