# Generated by Django 3.2.8 on 2022-08-18 06:29

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20220818_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='limitations',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
