# Generated by Django 3.2.8 on 2022-08-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20220817_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='discounts',
        ),
    ]
