# Generated by Django 3.2.8 on 2022-08-18 07:42

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_discountcode_limitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('lang', models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('id', 'Indonesian'), ('vi', 'Vietnam')], default='en', max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_sign', models.CharField(blank=True, default='$', max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, default='Asia/Singapore', max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('token_update_at', models.DateTimeField(null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('payment_meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'api_twitch_channel',
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='twitch_channels',
            field=models.ManyToManyField(related_name='user_subscriptions', to='api.TwitchChannel'),
        ),
    ]
