# Generated by Django 3.2.8 on 2022-08-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20220818_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchchannel',
            name='channel_name',
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
