# Generated by Django 3.2.8 on 2022-08-17 08:39

import api.models.campaign.discount
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20220817_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=djongo.models.fields.ArrayField(default=[], model_container=api.models.campaign.discount.Discount),
        ),
        migrations.AddField(
            model_name='preorder',
            name='discounts',
            field=djongo.models.fields.ArrayField(default=[], model_container=api.models.campaign.discount.Discount),
        ),
    ]
