# Generated by Django 3.2.8 on 2022-08-22 04:19

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20220822_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tiktok_campaign',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='twitch_campaign',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='twitch_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='api.twitchchannel'),
        ),
        migrations.AddField(
            model_name='twitchchannel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
