# Generated by Django 3.2.8 on 2022-08-23 06:20

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20220822_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('token_update_at', models.DateTimeField(null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'api_tiktok_account',
            },
        ),
    ]
