# Generated by Django 3.2.8 on 2022-08-31 04:02

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20220824_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', djongo.models.fields.JSONField(default=dict)),
                ('meta', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_developer',
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('trial', 'Trial'), ('lite', 'Lite'), ('standard', 'Standard'), ('premium', 'Premium'), ('dealer', 'Dealer')], default='trial', max_length=255, null=True)),
                ('period', models.CharField(blank=True, default='month', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timezone', models.CharField(blank=True, default='Asia/Singapore', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('target_country', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='SG', max_length=255, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'api_user_register',
            },
        ),
    ]
