# Generated by Django 3.2.8 on 2022-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_developer_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
