# Generated by Django 3.2.8 on 2022-08-31 08:41

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_developer_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='authorization',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='product', max_length=255, null=True),
        ),
    ]
