# Generated by Django 3.2.8 on 2022-09-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20220831_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='payment_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='status',
            field=models.CharField(blank=True, default='proceed', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='type',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_public_bucket/static/', max_length=255, null=True),
        ),
    ]
