# Generated by Django 3.2.8 on 2022-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20220905_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_public_bucket/static/no_image.jpeg', max_length=255, null=True),
        ),
    ]
