# Generated by Django 3.2.8 on 2022-09-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='oversell',
            field=models.BooleanField(default=True),
        ),
    ]
