# Generated by Django 3.2.8 on 2022-09-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20220913_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
