# Generated by Django 3.2.8 on 2022-09-20 07:01

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_deal_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='meta_reply',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='meta_reply',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
