# Generated by Django 3.2.8 on 2022-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20220920_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
