# Generated by Django 3.2.8 on 2022-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_discountcode_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='applied_count',
            field=models.IntegerField(default=0),
        ),
    ]
