# Generated by Django 3.2.8 on 2022-09-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_discountcode_applied_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='qty_pending_payment',
            field=models.IntegerField(default=0),
        ),
    ]
