# Generated by Django 3.2.8 on 2022-09-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_campaignproduct_qty_pending_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preorder',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
