# Generated by Django 3.2.8 on 2022-09-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20220929_0412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountcode',
            unique_together={('user_subscription', 'code')},
        ),
    ]
