# Generated by Django 3.2.8 on 2022-10-13 10:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_discountcode_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seller_adjust',
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='allow_add_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='adjust_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='adjust_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='applied_discount',
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
