# Generated by Django 3.2.8 on 2022-10-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20221013_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, default='awaiting_fulfillment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='awaiting_payment', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='type',
            field=models.CharField(blank=True, default='product', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='campaign_comment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='currency_sign',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_code',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='pre_order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
    ]
