# Generated by Django 3.2.8 on 2022-10-24 04:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20221020_0319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together=set(),
        )
    ]
