# Generated by Django 3.2.8 on 2022-10-24 05:08

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20221024_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_logistic', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('user_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='api.usersubscription')),
            ],
            options={
                'db_table': 'api_product_category',
                'unique_together': {('user_subscription', 'name')},
            },
        ),
    ]
