# Generated by Django 3.2.8 on 2022-11-09 07:27

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='meta_point',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='silent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='categories',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meta_point',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='point_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='point_expired_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='meta_point',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='BuyerWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(default='valid', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='api.user')),
                ('user_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_wallets', to='api.usersubscription')),
            ],
            options={
                'db_table': 'api_user_wallet',
                'unique_together': {('user_subscription', 'buyer')},
            },
        ),
    ]
