# Generated by Django 3.2.8 on 2022-11-10 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20221109_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='api.usersubscription'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.usersubscription'),
        ),
    ]
