# Generated by Django 3.2.8 on 2022-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20221110_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='decimal_places',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='price_unit',
            field=models.CharField(blank=True, default='1', max_length=255),
        ),
    ]
