# Generated by Django 3.2.8 on 2022-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20221111_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
