# Generated by Django 3.2.8 on 2022-11-16 06:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_orderproduct_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='buyer_usage',
            field=djongo.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/lss_public_bucket/static/no_image.jpeg', max_length=256, null=True),
        ),
    ]
