# Generated by Django 3.2.8 on 2022-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20221116_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='period_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
