# Generated by Django 3.2.8 on 2022-11-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_discountcode_period_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='customers',
            field=models.ManyToManyField(related_name='stores', to='api.User'),
        ),
    ]
