# Generated by Django 3.2.8 on 2022-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_usersubscription_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
