# Generated by Django 3.2.8 on 2022-11-21 05:39

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_order_shipping_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='meta_remind',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='meta_store',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
