# Generated by Django 3.2.8 on 2022-11-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20221121_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='meta_remind',
        ),
    ]
