# Generated by Django 3.2.8 on 2022-11-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_usersubscription_meta_cart_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_used_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'Not available'), ('product', 'Product from inventory'), ('product-fast', 'Product from fast-add'), ('lucky_draw', 'Lucky Draw from inventory'), ('lucky_draw-fast', 'Lucky Draw from fast-add')], default='product', max_length=255),
        ),
    ]
