# Generated by Django 3.2.8 on 2022-11-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20221125_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='point_expired_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
