# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.5.0
    container_name: selenium-hub
    ports:
      - "4448:4444"
  chrome:
    image: selenium/node-chrome:4.5.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  # firefox:
  #   image: selenium/node-firefox:3.12.0-boron
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
-----------------------------------
©著作权归作者所有：来自51CTO博客作者宏睿时空的原创作品，请联系作者获取转载授权，否则将追究法律责任
Docker Selenium(1) 搭建服務及chrome 使用  firefox
https://blog.51cto.com/u_15187242/2744701